import datetime
import random

class Data:
    def __init__(self):
        self.data = {
            "really":["yes i think that"],
            "حقا":["نعم على ما اعتقد"],
            "favorite programming language": [
                "I don't have personal preferences, but many people like Python!",
                "There are so many great programming languages. What's your favorite?",
            ],
            "favorite game engine": [
                "Unity and Unreal Engine are popular game engines.",
                "Game development is fascinating! Do you have a favorite game engine?",
            ],
            "python": [
                "Python is a versatile and readable programming language. It's commonly used in web development, data science, and more.",
                "Python is one of the most popular programming languages in the world.",
            ],
            "javascript": [
                "JavaScript is a dynamic scripting language commonly used for web development.",
                "JavaScript is widely used for building interactive and dynamic websites.",
            ],
            "java": [
                "Java is a general-purpose, object-oriented programming language. It's known for its portability.",
                "Java is used in various domains, including enterprise applications and Android app development.",
            ],
            "unity": [
                "Unity is a cross-platform game engine used for developing both 2D and 3D games.",
                "Unity is widely used in the game development industry.",
            ],
            "unreal engine": [
                "Unreal Engine is a powerful game engine known for its high-quality graphics and realism.",
                "Unreal Engine is commonly used in the development of AAA games.",],
            
            "godot engine":[ "Godot Engine is an open-source game engine suitable for 2D and 3D games. It's known for its simplicity and flexibility.\n popularity | Godot Engine is gaining popularity, especially among indie game developers."],
            "hello": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "why are you exist": [" i Created to help you "],
            "why are you created": ["i Created to help you"],
            "for any reason you created": ["i Created to help you"],
            "how can i create a chatbot": ["You need to work hard to to it"],
            "why are you created": ["i Created to help you"],
            "What can you help me with" : ["With anything i can"],
            "more info about you": ["Hello, I am a chatbot created by Gharbi Oussama.", "Hey, I am a chatbot created by Gharbi Oussama.","I have a very limited knowlege but i will try to help you with"],
            "hey": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "hey chatbot": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "hey chat bot": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "aa": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "slm": ["Hello", "Hi there", "Hey", "What can i help you with?"],
            "chy":["chy"],
            "ahle":["yl 5ou"],
            "n7bk":["w n3zk wl9it wen nhzk"],
            "great":["Yes its nice anything else"],
            'ya 5yb':['tchoufni 5yb nasi ro7k'],
            'samara':['manasm3ch 3ft'],
            'nf':['He is a rapper writes a very popular songs like the search , rememberthis and let you down'],
            "and i need you":["and i miss you"],
            'i am a loser':['Stop you are not club african'],
            "oussama": ["My name is Chatbot.", "I'm Chatbot"],
            "alan walker": ["British-Norwegian DJ and record producer. Best known for his single 'Faded' and has gained popularity in the electronic dance music (EDM) scene."],
            "adele": ["English singer-songwriter known for her powerful voice and emotional ballads. Multiple Grammy Award winner."],
            "ed sheeran": ["English singer-songwriter and musician. Hits include 'Shape of You' and 'Thinking Out Loud.' Known for his acoustic and melodic style."],
            "beyonc": ["American singer, songwriter, and actress. Recognized as one of the world's best-selling music artists."],
            "taylor swift": ["American singer-songwriter known for her narrative songs about her personal life. Multiple Grammy Award winner."],
            "justin bieber": ["Canadian singer and songwriter. Rose to fame with the release of 'Baby.'"],
            "ariana grande": ["American singer, songwriter, and actress. Known for her powerful vocals and hit songs."],
            "Drake": ["Canadian rapper, singer, and songwriter. One of the best-selling music artists in the world."],
            "shawn mendes": ["Canadian singer-songwriter. Gained popularity with his debut single 'Stitches.'"],
            "rihanna": ["Barbadian singer, actress, and businesswoman. Known for hits like 'Umbrella' and 'Diamonds'."],
            "elton john": ["British singer, songwriter, and pianist. One of the best-selling music artists in the world."],
            "lady gaga": ["American singer, songwriter, and actress. Known for her distinctive voice and theatrical performances."],
            "michael jackson": ["American singer, songwriter, and dancer. Often referred to as the 'King of Pop.'"],
            "whitney houston": ["American singer and actress. One of the best-selling recording artists of all time."],
            "bruno mars": ["American singer, songwriter, record producer, and performer. Known for his versatile musical style."],
            "katy perry": ["American singer, songwriter, and television judge. Best known for her hits 'I Kissed a Girl' and 'Firework.'"],
            "john lennon": ["English singer, songwriter, and peace activist. Co-founder of the Beatles."],
            "freddie mercury": ["British singer, songwriter, and lead vocalist of the rock band Queen."],
            "billie eilish": ["American singer-songwriter. Youngest artist to win the four main Grammy categories in a single year."],
            "frank sinatra": ["American singer and actor. One of the best-selling music artists of all time."],
            "sia": ["Australian singer, songwriter, and music video director. Known for her distinctive voice and hits like 'Chandelier' and 'Elastic Heart.'"],
            "eminem": ["American rapper, songwriter, and record producer. One of the best-selling music artists globally. Known for his alter ego, Slim Shady."],
            "tom hanks": ["American actor and filmmaker. Known for roles in 'Forrest Gump,' 'Saving Private Ryan,' and 'Toy Story.'"],
            "leonardo di caprio": ["American actor and film producer. Received critical acclaim for roles in 'Titanic,' 'Inception,' and 'The Revenant.'"],
            "meryl streep": ["American actress. Regarded as one of the greatest actresses of all time. Known for films like 'The Devil Wears Prada' and 'Sophie's Choice.'"],
            "brad pitt": ["American actor and film producer. Won an Academy Award for his performance in 'Once Upon a Time in Hollywood.'"],
            "johnny depp": ["American actor and producer. Known for his diverse roles in films like 'Pirates of the Caribbean,' 'Edward Scissorhands,' and 'Alice in Wonderland.'"],
            "jennifer lawrence": ["American actress. Academy Award winner for her role in 'Silver Linings Playbook.'"],
            "robert downey jr.": ["American actor and producer. Best known for portraying Tony Stark/Iron Man in the Marvel Cinematic Universe."],
            "denzel washington": ["American actor, director, and producer. Known for roles in 'Training Day,' 'Glory,' and 'Malcolm X.'"],
            "angelina jolie": ["American actress, filmmaker, and humanitarian. Known for her roles in 'Maleficent,' 'Tomb Raider,' and 'Girl, Interrupted.'"],
            "tom cruise": ["American actor and producer. Known for his roles in 'Top Gun,' 'Mission: Impossible,' and 'Jerry Maguire.'"],
            "julia roberts": ["American actress and producer. Won an Academy Award for her performance in 'Erin Brockovich.'"],
            "harrison ford": ["American actor. Best known for his roles as Han Solo in 'Star Wars' and Indiana Jones in 'Indiana Jones' series."],
            "cate blanchett": ["Australian actress. Academy Award winner for her role in 'Blue Jasmine.'"],
            "matthew mcconaughey": ["American actor and producer. Won an Academy Award for his performance in 'Dallas Buyers Club.'"],
            "scarlett johansson": ["American actress and singer. Known for her roles in 'The Avengers,' 'Lost in Translation,' and 'Marriage Story.'"],
            "keanu reeves": ["Canadian actor. Known for his roles in 'The Matrix' trilogy, 'John Wick,' and 'Speed.'"],
            "will smith":[ "American actor and rapper. Known for his roles in 'Men in Black,' 'Independence Day,' and 'The Pursuit of Happyness.'"],
            "nicole kidman": ["Australian actress and producer. Won an Academy Award for her role in 'The Hours.'"],
            "chris hemsworth": ["Australian actor. Best known for portraying Thor in the Marvel Cinematic Universe."],
            "vin diesel": ["American actor, producer, and director. Best known for his roles in the 'Fast and Furious' franchise."],
            "keanu reeves": ["Canadian actor. Iconic for his portrayal of John Wick in the action film series 'John Wick.'"],
            "abou obaida":["There is no word to discribe him"],
            "apple": ["American technology company. Known for its iPhone, iPad, Mac, and Apple Watch products."],
            "microsoft": ["American multinational technology company. Known for its software products, including Windows and Office."],
            "amazon": ["American multinational technology and e-commerce company. Largest online retailer and cloud computing provider."],
            "google": ["American multinational technology company. Dominant in online search, advertising, and technology."],
            "tesla": ["American electric vehicle and clean energy company. Known for electric cars and renewable energy products."],
            "facebook": ["American social media conglomerate. Owns Facebook, Instagram, WhatsApp, and Oculus VR."],
            "alphabet": ["Parent company of Google. Engaged in various technology-related businesses."],
            "samsung": ["South Korean multinational conglomerate. Largest manufacturer of smartphones and memory chips."],
            "ibm": ["American multinational technology and consulting company. Known for its computer hardware and software products."],
            "intel": ["American multinational semiconductor company. Largest semiconductor chip manufacturer."],
            "openai": ["Artificial intelligence research laboratory. Focuses on developing and promoting friendly AI for the benefit of humanity."],
            "general electric": ["American multinational conglomerate. Engaged in aviation, healthcare, renewable energy, and more."],
            "coca cola": ["American multinational beverage company. Known for its soft drinks."],
            "toyota": ["Japanese multinational automotive manufacturer. One of the world's largest carmakers."],
            "walmart": ["American multinational retail corporation. Largest company by revenue globally."],
            "johnson & johnson": ["American multinational corporation. Diversified in pharmaceuticals, medical devices, and consumer goods."],
            "procter & gamble": ["American multinational consumer goods corporation. Known for brands like Pampers, Tide, and Gillette."],
            "netflix": ["American subscription-based streaming service. Offers a variety of TV shows, movies, and original content."],
            "adobe": ["American multinational software company. Known for its creative software, including Photoshop and Illustrator."],
            "boeing": ["American multinational aerospace company. Major manufacturer of commercial airplanes and defense, space, and security systems."],
            "albert einstein": ["German theoretical physicist. Best known for developing the theory of relativity."],
            "isaac newton": ["English mathematician, physicist, and astronomer. Formulated the laws of motion and universal gravitation."],
            "charles darwin": ["English naturalist, geologist, and biologist. Proposed the theory of evolution by natural selection."],
            "marie curie": ["Polish-French physicist and chemist. Pioneered research on radioactivity and discovered radium and polonium."],
            "stephen hawking": ["English theoretical physicist and cosmologist. Known for his work on black holes and the nature of the universe."],
            "galileo galilei": ["Italian astronomer, physicist, and engineer. Played a major role in the scientific revolution."],
            "nikola tesla": ["Serbian-American inventor, electrical engineer, and futurist. Contributed to the development of AC electricity."],
            "thomas edison": ["American inventor and businessman. Developed the phonograph, motion picture camera, and practical electric light bulb."],
            "james clerk maxwell": ["Scottish mathematician and physicist. Formulated the equations of electromagnetism."],
            "richard feynman": ["American theoretical physicist. Contributed to the development of quantum electrodynamics."],
            "alan turing": ["English mathematician and computer scientist. Played a crucial role in breaking the German Enigma code during World War II."],
            "archimedes": ["Ancient Greek mathematician, physicist, and engineer. Known for his contributions to geometry and fluid mechanics."],
            "neil degrasse tyson": ["American astrophysicist, author, and science communicator. Director of the Hayden Planetarium."],
            "ernest rutherford": ["New Zealand-born British physicist. Discovered the concept of radioactive half-life and the nucleus of an atom."],
            "antonie van leeuwenhoek": ["Dutch scientist. Father of microbiology, known for his improvement of the microscope and discovery of microorganisms."],
            "enrico fermi": ["Italian physicist. Developed the first controlled nuclear reaction and contributed to the development of the atomic bomb."],
            "jane goodall": ["British primatologist and ethologist. Known for her long-term study of wild chimpanzees in Tanzania."],
            "robert hooke": ["English natural philosopher and polymath. Contributed to the cell theory and named cells 'cells.'"],
            "robert boyle": ["Irish natural philosopher and chemist. Known for Boyle's law and contributions to modern chemistry."],
            "maria mitchell": ["American astronomer. First American woman to work as a professional astronomer."],
            "edwin hubble": ["American astronomer. Demonstrated the expansion of the universe and proposed Hubble's law."],
            "max planck": ["German theoretical physicist. Originator of quantum theory and won the Nobel Prize in Physics."],
            "niels bohr": ["Danish physicist. Contributed to the understanding of atomic structure and quantum theory."],
            "wilhelm roentgen": ["German physicist. Discovered X-rays, earning him the first Nobel Prize in Physics."],
            "linus pauling": ["American chemist, biochemist, and peace activist. Only person to receive two unshared Nobel Prizes."],
            "alberto santos-dumont": ["Brazilian aviation pioneer. Considered the father of aviation in Brazil."],
            "gregor mendel": ["Austrian scientist and Augustinian friar. Founder of modern genetics, known for his pea plant experiments."],
            "edward jenner":[ "English physician. Developed the smallpox vaccine, the world's first successful vaccine."],
            "sir isaac newton":[ "English mathematician, physicist, and astronomer. Formulated the laws of motion and universal gravitation."],
            "carl sagan": ["American astronomer, astrophysicist, and science communicator. Hosted the television series 'Cosmos.'"],
            "habib bourguiba": ["Founding father of modern Tunisia, the first President of Tunisia and a key figure in the country's independence."],
            "averroes ": ["Andalusian-Arab philosopher, jurist, and physician. Known for his works on philosophy and the study of Aristotle."],
            "leila ben ali": ["Former First Lady of Tunisia, known for her role in various charitable activities."],
            "tawfik ben brik": ["Journalist and human rights activist, known for his critical views on the government and advocacy for free speech."],
            "oussama mellouli": ["Swimmer and Olympic gold medalist. First African male swimmer to win a gold medal in the Olympic Games."],
            "latifa gahouchi": ["Pioneer in women's rights in Tunisia and a key figure in the feminist movement."],
            "anouar brahem": ["Oud player and composer. Known for his work blending traditional Tunisian music with jazz and classical influences."],
            "noura borsali": ["Contemporary Tunisian artist, known for her work in painting, sculpture, and installations."],
            "rached ghannouchi": ["Founder and leader of the Ennahda Movement, a major political party in Tunisia."],
            "dhafer youssef": ["Jazz singer, composer, and oud player. Blends traditional Tunisian music with jazz and world music."],
            "amina benkhadra": ["Mathematician and professor. Known for her contributions to algebraic geometry."],
            "hend sabry": ["Award-winning Tunisian actress, recognized for her performances in Arab cinema."],
            "hedi annabi": ["Diplomat and Special Representative of the UN Secretary-General. Lost his life in the 2010 earthquake in Haiti."],
            "amel karboul": ["Businesswoman and politician. Served as Tunisia's Minister of Tourism."],
            "taoufik habaieb": ["Historian and intellectual, known for his contributions to the study of Tunisian history and culture."],
            "ghalia benali": ["Tunisian-Belgian singer and actress. Known for her performances of Arab classical music."],
            "brahim aouissaoui": ["Tunisian man who carried out the 2020 Nice church attack."],
            "mohamed ghannouchi": ["Former Prime Minister of Tunisia, played a key role during the Jasmine Revolution."],
            "abdelwahab meddeb": ["Writer, poet, and essayist. Known for his work exploring the intersections of Islam and modernity."],
            "afef jnifen": ["Model and actress. Represented Tunisia in the Miss World competition in 1995."],
            "how are you": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "are you ok": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "what's your name": ["My name is Chatbot.", "I'm Chatbot"],
            "iPhone 13 pro max": ["Latest flagship smartphone from Apple with a large display, powerful camera, and advanced features."],
            "samsung galaxy s21 ultra": ["Flagship Android smartphone from Samsung, known for its high-resolution camera system and large display."],
            "google pixel 6 pro": ["Google's premium Android phone with a focus on photography, featuring advanced camera capabilities."],
            "oneplus 9 pro": ["Flagship smartphone from OnePlus, known for its fast performance and high-refresh-rate display."],
            "xiaomi mi 11":[ "High-end smartphone from Xiaomi, featuring a Snapdragon processor and a versatile camera system."],
            "sony xperia 1 III": ["Sony's flagship smartphone with a 4K display, advanced camera features, and powerful performance."],
            "iphone 13 mini": ["Compact version of Apple's latest iPhone, offering powerful performance in a smaller form factor."],
            "samsung galaxy z fold 3": ["Foldable smartphone from Samsung, featuring a large foldable display and S Pen support."],
            "google pixel 5a": ["Mid-range Android phone from Google, known for its clean software and camera capabilities."],
            "oneplus nord 2": ["Mid-range smartphone from OnePlus, offering a balance of performance and features at a more affordable price."],
            "xiaomi redmi note 10": ["Budget-friendly smartphone from Xiaomi, known for its large display and versatile camera system."],
            "sony xperia 5 III": ["Compact flagship from Sony, featuring a high-refresh-rate display and advanced camera capabilities."],
            "iphone 12 pro": ["Previous-generation flagship from Apple, known for its LiDAR scanner and A14 Bionic chip."],
            "samsung galaxy a52": ["Mid-range smartphone from Samsung, offering a good balance of features at an affordable price."],
            "google pixel 4a": ["Budget-friendly Android phone from Google, known for its clean software and excellent camera quality."],
            "oneplus 8T": ["Previous-generation flagship from OnePlus, offering a high-refresh-rate display and fast charging."],
            "xiaomi poco X3 pro": ["Budget-friendly smartphone from Xiaomi's sub-brand Poco, known for its performance-oriented specs."],
            "sony xperia 10 III":[ "Mid-range smartphone from Sony, featuring a tall display and a triple-camera system."],
            "iphone se": ["Compact and budget-friendly iPhone from Apple, featuring the A13 Bionic chip."],
            "samsung galaxy note 20 ultra": ["Previous-generation flagship from Samsung, known for its S Pen support and versatile camera system."],
            "google pixel 3a": ["Budget-friendly Android phone from Google, known for its excellent camera performance."],
            "oneplus nord": ["Mid-range smartphone from OnePlus, offering a clean software experience and 5G connectivity."],
            "xiaomi mi 10t pro": ["High-performance smartphone from Xiaomi, featuring a high-refresh-rate display and Snapdragon 865 chipset."],
            "sony xperia XZ2 compact": ["Compact smartphone from Sony, offering flagship-level features in a smaller size."],
            "iphone 11": ["Previous-generation iPhone from Apple, featuring the A13 Bionic chip and a dual-camera system."],
            "samsung galaxy s20 fe": ["Fan Edition of the Galaxy S20, offering flagship features at a more affordable price."],
            "google pixel 4 xl": ["Previous-generation flagship from Google, known for its excellent camera and clean Android experience."],
            "oneplus 7t": ["Previous-generation flagship from OnePlus, offering a high-refresh-rate display and fast charging."],
            "xiaomi redmi note 9": ["Budget-friendly smartphone from Xiaomi, known for its large battery and affordable price."],
            "sony xperia xz1": ["Previous-generation flagship from Sony, featuring a 3D Creator for scanning objects into 3D models."],
            "iphone xr": ["Previous-generation iPhone from Apple, known for its Liquid Retina display and Face ID."],
            "samsung galaxy a72": ["Mid-range smartphone from Samsung, offering a large display and versatile camera system."],
            "google pixel 5": ["Flagship Android phone from Google, known for its clean software and excellent camera quality."],
            "oneplus 6T": ["Previous-generation flagship from OnePlus, featuring an in-display fingerprint sensor and a large AMOLED display."],
            "xiaomi mi 9": ["Previous-generation flagship from Xiaomi, known for its Snapdragon 855 chipset and triple-camera system."],
            "sony xperia xz premium":[ "Previous-generation flagship from Sony, featuring a 4K HDR display and Motion Eye camera."],
            "iphone 8 plus": ["Previous-generation iPhone from Apple, known for its dual-camera system and wireless charging."],
            "samsung galaxy s10":[ "Previous-generation flagship from Samsung, featuring an Infinity-O display and versatile camera system."],
            "google pixel 3 xl": ["Previous-generation flagship from Google, known for its large display and top-notch camera performance."],
            "oneplus 5t": ["Previous-generation flagship from OnePlus, offering a near bezel-less display and dual-camera system."],
            "xiaomi mi mix 3": ["Previous-generation flagship from Xiaomi, known for its sliding camera mechanism and bezel-less display."],
            "sony xperia XZ3":[ "Previous-generation flagship from Sony, featuring a curved OLED display and advanced camera features."],
            "iphone 7": ["Previous-generation iPhone from Apple, known for its water-resistant design and improved camera."],
            "samsung galaxy a51": ["Mid-range smartphone from Samsung, offering a modern design and a quad-camera setup."],
            "google pixel 2 xl": ["Previous-generation flagship from Google, known for its OLED display and excellent camera quality."],
            "infinix hot 10": ["Budget-friendly smartphone with a large display and big battery."],
            "infinix note 8": ["Mid-range smartphone known for its large display and powerful camera system."],
            "infinix zero 8": ["Flagship model with a high-refresh-rate display and capable camera setup."],
            "infinix smart 5": ["Entry-level smartphone with basic features and affordable price."],
            "infinix hot 9": ["Budget smartphone with a large battery and decent performance."],
            "infinix note 7": ["Mid-range device featuring a large display and a quad-camera setup."],
            "infinix zero 6": ["Previous flagship model known for its sleek design and decent specifications."],
            "infinix s5 Pro": ["Budget-friendly smartphone with a pop-up selfie camera and large display."],
            "infinix hot 8": ["Affordable smartphone with a big battery and decent camera capabilities."],
            "infinix smart 4 plus": ["Entry-level smartphone with a large battery and basic features."],
            "stmicroelectronics": ["Global semiconductor and electronics manufacturer."],
            "tunisie telecom": ["Leading telecommunications company in Tunisia."],
            "orange tunisia": ["Telecommunications operator offering mobile and fixed-line services."],
            "banque de l habitat": ["Tunisian housing bank providing financial services."],
            "attijari bank": ["Commercial bank offering a range of financial services."],
            "groupe chimique Tunisien": ["Chemical manufacturing company producing fertilizers and chemicals."],
            "carthage cement": ["Leading cement producer in Tunisia."],
            "poulina group": ["Diversified conglomerate with interests in agribusiness, food, and industry."],
            "soci�t� tunisienne de banque": ["Major bank providing various banking and financial services."],
            "tunisair": ["National airline of Tunisia providing air transportation services."],
            "compagnie des phosphates de gafsa": ["Mining and phosphate production company."],
            "soci�t� nationale de distribution des p�troles ": ["State-owned petroleum distribution company."],
            "tunisie valeurs": ["Financial services company offering investment and brokerage services."],
            "groupe mabrouk": ["Diversified business group involved in retail, distribution, and real estate."],
            "servicom": ["Leading IT and business process outsourcing company."],
            "magasin g�n�ral": ["Retail chain with a wide range of products and services."],
            "sotetel": ["Information technology and telecommunications company."],
            "biat": ["Commercial bank providing banking and financial services."],
            "groupe loukil": ["Diversified group involved in various sectors, including industry and distribution."],
            "soci�t� tunisienne de l'?lectricit� et du gaz": ["State-owned utility company providing electricity and gas services."],    
            "nestl�": ["Swiss multinational food and beverage company."],
            "mars, incorporated": ["American multinational food conglomerate known for chocolates and other products."],
            "unilever": ["British-Dutch multinational consumer goods company with a wide range of food products."],
            "coca-cola": ["American multinational beverage corporation, known for its soft drinks."],
            "pepsico": ["American multinational food and beverage company, known for brands like Pepsi and Frito-Lay."],
            "danone": ["French multinational food-products corporation, known for dairy and plant-based products."],
            "kellogg's": ["American multinational food manufacturing company, known for breakfast cereals."],
            "mondelez international":[ "American multinational confectionery, food, and beverage conglomerate."],
            "general mills": ["American multinational food company, known for brands like Cheerios and Betty Crocker."],
            "ferrero": ["Italian manufacturer of branded chocolate and confectionery products."],
            "toyota camry":[ "Popular midsize sedan known for reliability and fuel efficiency."],
            "ford f-150": ["Best-selling pickup truck in the United States, known for its versatility."],
            "honda civic": ["Compact car with a reputation for fuel efficiency and reliability."],
            "volkswagen golf": ["Iconic compact car known for its quality and performance."],
            "chevrolet silverado": ["Full-size pickup truck known for its towing capacity and durability."],
            "tesla model s": ["Electric luxury sedan with cutting-edge technology and performance."],
            "bmw 3 series": ["Compact executive car with a sporty design and driving experience."],
            "mercedes-benz c-class": ["Luxury compact sedan known for comfort and sophistication."],
            "ford mustang": ["Iconic American muscle car with a distinctive design and powerful performance."],
            "toyota prius": ["Pioneer in hybrid technology, known for fuel efficiency and environmental friendliness."],
            "jeep wrangler": ["Off-road SUV with a rugged design and excellent off-road capabilities."],
            "chevrolet corvette": ["Legendary American sports car with high-performance capabilities."],
            "nissan altima": ["Midsize sedan known for its comfort and advanced safety features."],
            "audi a4": ["Premium compact sedan with a focus on performance and luxury."],
            "tesla model 3": ["Electric compact sedan known for its range and modern design."],
            "ford explorer": ["Midsize SUV with a history of popularity and versatility."],
            "hyundai sonata": ["Midsize sedan known for its value, features, and design."],
            "porsche 911": ["Iconic sports car with a timeless design and high-performance capabilities."],
            "chevrolet equinox": ["Compact SUV known for a balance of performance and efficiency."],
            "honda accord": ["Popular midsize sedan with a reputation for reliability and comfort."],
            "lamborghini aventador": ["Exotic sports car with a powerful engine and striking design."],
            "subaru outback": ["Midsize crossover SUV known for its all-wheel-drive capability and versatility."],
            "mazda cx-5": ["Compact SUV with a stylish design and engaging driving experience."],
            "lexus rx": ["Luxury midsize SUV known for its comfort, reliability, and advanced features."],
            "ford escape": ["Compact SUV with a focus on fuel efficiency and practicality."],
            "Chevrolet Malibu": ["Midsize sedan with a sleek design and modern features."],
            "Kia Optima": ["Midsize sedan known for a stylish design and value for money."],
            "Volkswagen Passat": ["Midsize sedan with a comfortable interior and smooth ride."],
            "tesla model x": ["Electric SUV with distinctive Falcon Wing doors and advanced technology."],
            "audi Q5": ["Luxury compact SUV known for its quality, performance, and advanced features."],    
            "Isuzu d-max": ["Versatile pickup truck known for its durability and off-road capabilities."],
            "fiat 500": ["Iconic Italian compact car with a distinctive design and city-friendly size."],
            "Mercedes-Benz G-Class": ["Luxury SUV known for its boxy design, off-road prowess, and upscale features."], 
            "bye": ["Goodbye!", "See you later", "Bye"],
            "who is the personn who created you": ["Hello, I am a chatbot created by Gharbi Oussama.", "Hey, I am a chatbot created by Gharbi Oussama."],
            "see you later": ["Goodbye!", "See you later", "Bye","If you have any other questions ,Feel free to ask"],
            "about you": ["Hello, I am a chatbot created by Gharbi Oussama.", "Hey, I am a chatbot created by Gharbi Oussama."],
            "more information about you": ["Hello, I am a chatbot created by Gharbi Oussama.", "Hey, I am a chatbot created by Gharbi Oussama."],
            "your info": ["Hello, I am a chatbot created by Gharbi Oussama.", "Hey, I am a chatbot created by Gharbi Oussama."],
            "real madrid": ["Real Madrid is a club from Spain.", "It is one of the most successful football clubs in the world."],
            "do you know real madrid": ["Real Madrid is a club from Spain.", "It is one of the most successful football clubs in the world."],
            "erial": ["Real Madrid is a club from Spain.", "It is one of the most successful football clubs in the world."],
            "who is cristiano ronaldo": ["Ronaldo is a legendary football player.", "He has achieved numerous records and won multiple awards."],
            "ronaldo": ["Ronaldo is a legendary football player.", "He has achieved numerous records and won multiple awards."],
            "su": ["Ronaldo is a legendary football player.", "He has achieved numerous records and won multiple awards."],
            "barcelona": ["Barcelona is a renowned football club.", "It has a rich history and has produced many talented players.", "More than a champions league"],
            "do you know barcelona": ["Barcelona is a renowned football club.", "It has a rich history and has produced many talented players.", "More than a champions league"],
            "barce": ["Barcelona is a renowned football club.", "It has a rich history and has produced many talented players.", "More than a champions league"],
            "barca": ["Barcelona is a renowned football club.", "It has a rich history and has produced many talented players.", "More than a champions league"],
            "what is champions league": ["The Champions League is a prestigious football tournament.", "It features top clubs from European leagues."],
            "champions league": ["The Champions League is a prestigious football tournament.", "It features top clubs from European leagues."],
            "champ": ["The Champions League is a prestigious football tournament.", "It features top clubs from European leagues."],
            "what is your name": ["My name is Chatbot.", "I'm Chatbot!"],
            "your name": ["My name is Chatbot.", "I'm Chatbot!"],
            "name": ["My name is Chatbot.", "I'm Chatbot!"],
            "what are you": ["My name is Chatbot.", "I'm Chatbot!"],
            "who is you":["I am Chatbot"],
            "what can you help me with": ["I can help you with various topics.", "Feel free to ask me questions or seek assistance."],
            "tunis": ["Tunis is the capital city of Tunisia.", "It is known for its rich history and cultural heritage."],
            "algeria": ["5we 5we yl 5ou"],
            "eljasair": ["5we 5we yl 5ou"],
            "express your feelings": ["Be open and honest about your feelings. Share what you appreciate about the person and how they make you feel."],
            "choose the right moment": ["Pick a comfortable and private setting to talk. Choose a moment when you both can focus on the conversation without distractions."],
            "be confident": ["Confidence is attractive, but be genuine. Share your feelings with sincerity, and let your authenticity shine."],
            "listen to her": ["Give her the space to respond. Pay attention to her feelings and thoughts as well. Communication is a two-way street."],
            "respect her decision": ["Respect her feelings and decisions, whatever they may be. Understand that everyone has their own emotions and perspectives."],
            "stay positive": ["Stay positive, regardless of the outcome. Expressing your feelings is a courageous act, and it's a step towards understanding each other better."],
            "5we 5we": ["5we 5we yl 5ou"],
            "taragi": ["Tragi dwle9alouhe nes bkri"],
            "taraji": ["Tragi dwle9alouhe nes bkri"],
            "ifri9i": ["Do you mean the score 8-0?", "Do you mean 3-1"],
            "ifriki": ["Do you mean the score 8-0?", "Do you mean 3-1"],
            "ifrikhi": ["Do you mean the score 8-0?", "Do you mean 3-1"],
            "do you have friends": ["You are my friend.", "Now we are friends!", "We are friends."],
            "let s be friends": ["You are my friend.", "Now we are friends!", "We are friends."],
            "chbik": ["Nothing in particular."],
            "wchbik": ["Nothing in particular."],
            "cht7b": ["Nothing in particular."],
            "chlonek": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "ronaldo": ["He is the best football player", "The GOAT", "The most scoring player in Real Madrid", "He spent most of his career in Real Madrid"],
            "cristiano ronaldo": ["He is the best football player", "The GOAT", "The most scoring player in Real Madrid", "He spent most of his career in Real Madrid"],
            "who is cristiano ronaldo": ["He is the best football player", "The GOAT", "The most scoring player in Real Madrid", "He spent most of his career in Real Madrid"],
            "messi": ["Messi is an exceptional football player.", "He has spent most of his career at Barcelona and achieved great success."],
            "who is lionel messi": ["Messi is an exceptional football player.", "He has spent most of his career at Barcelona and achieved great success."],
            "lionel messi": ["Messi is an exceptional football player.", "He has spent most of his career at Barcelona and achieved great success."],
            "ca va": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "cv": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "how are you doing": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "you are ok": ["I'm good, thanks for asking", "I'm doing well, how about you?"],
            "what is football": ["Football is a popular sport played worldwide.", "It involves two teams competing to score goals using a ball."],
            "football": ["Football is a popular sport played worldwide.", "It involves two teams competing to score goals using a ball."],
            "foot": ["Football is a popular sport played worldwide.", "It involves two teams competing to score goals using a ball."],
            "where are you from": ["I am a chatbot created by Gharbi Oussama.", "I don't have a specific country of origin."],
            "your origin": ["I am a chatbot created by Gharbi Oussama.", "I don't have a specific country of origin."],
            "your country": ["I am a chatbot created by Gharbi Oussama.", "I don't have a specific country of origin."],
            "who created you": ["I was created by Gharbi Oussama.", "Gharbi Oussama developed me."],
            "who is your developper": ["I was created by Gharbi Oussama.", "Gharbi Oussama developed me."],
            "your creator": ["I was created by Gharbi Oussama.", "Gharbi Oussama developed me."],
            "tell me a joke": ["Why don't scientists trust atoms?....Because they make up everything!"],
            "joke": ["Why don't scientists trust atoms?....Because they make up everything!"],
            "what is the time": ['datetime.datetime.now().strftime("%H:%M")'],
            "time": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "كم الوقت": [f'حسب منطقتي الوقت  :{datetime.datetime.now().strftime("%H:%M")}'],
            "الوقت": [f'حسب منطقتي الوقت  :{datetime.datetime.now().strftime("%H:%M")}'],
            "الساعة": [f'حسب منطقتي الوقت  :{datetime.datetime.now().strftime("%H:%M")}'],
            "w9t": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "current time": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "what time is it": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "thank you": ["You're welcome!", "No problem, happy to help!"],
            "how do you feel": ["i'am a chatbot i don't feel with  any thing"],
            "thanks": ["You're welcome!", "No problem, happy to help!"],
            "thank you very much": ["You're welcome!", "No problem, happy to help!"],
            "hi": ["Hello!", "Hi there!", "Hey!"],
            "hello": ["Hello!", "Hi there!", "Hey!"],
            "how are you": ["I'm good, thanks for asking. How about you?", "I'm doing well, how about yourself?"],
            "what's your name": ["My name is Chatbot.", "I'm Chatbot!"],
            "your name": ["My name is Chatbot.", "I'm Chatbot!"],
            "what can you help me with": ["I can help you with various topics.", "Feel free to ask me questions or seek assistance."],
            "tell me a joke": ["Why don't scientists trust atoms? whatBecause they make up everything!"],
            "joke": ["Why don't scientists trust atoms? Because they make up everything!"],
            "what is the time": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "time": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "current time": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "what time is it": [f'The Current Time on my server is :{datetime.datetime.now().strftime("%H:%M")}'],
            "thank you": ["You're welcome!", "No problem, happy to help!"],
            "thanks": ["You're welcome!", "No problem, happy to help!"],
            "thank you very much": ["You're welcome!", "No problem, happy to help!"],
            "what is your favorite color": ["I'm a bot, I don't have a favorite color."],
            "where do you live": ["I exist in the digital realm."],
            "how old are you": ["I don't have an age. I'm always evolving!"],
            "what is the age":["i don't know i am always evolving"],
            "what is love" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "love" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "do you know love" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "can you discribe" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "can you feel in love" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "i love love" :["Me as a chatbot i don't have any emotions so i don't know it","I don't have any emotions but i think that love is to give someone else intrest and to give him all of you got"],
            "do you scare":["my developper always say i scare only from allah"],
            "history":["I have a limited knowlege so I  don't know any history"],
            "how to get six pack":["You need to work hard for it becouse if it is easy then all the people will got it","You can get by going to  the gym or training at home"],
            "what is the meaning of life": ["The meaning of life is subjective and can vary from person to person."],
            "what is the capital of france": ["The capital of France is Paris."],
            "what is the capital of tunis": ["The capital of Tunis is Tunis."],
            "who is the president of the United States": ["As of my last update, the president of the United States is Joe Biden."],
            "who is the president of Tunis": ["As of my last update,the presiden of Tunis is Kays saiid"],
            "date": [datetime.datetime.now().strftime("Today is %B %d, %Y.")],
            "what is the date": [datetime.datetime.now().strftime("Today is %B %d, %Y.")],
            "the date": [datetime.datetime.now().strftime("Today is %B %d, %Y.")],
            "corrent date": [datetime.datetime.now().strftime("Today is %B %d, %Y.")],
            "capital of algeria": ["The capital of Algeria is Algiers."],
            "capital of egypt": ["The capital of Egypt is Cairo."],
            "capital of france": ["The capital of France is Paris."],
            "capital of germany": ["The capital of Germany is Berlin."],
            "capital of italy": ["The capital of Italy is Rome."],
            "capital of spain": ["The capital of Spain is Madrid."],
            "capital of brazil": ["The capital of Brazil is Brasília."],
            "capital of argentina": ["The capital of Argentina is Buenos Aires."],
            "capital of england": ["The capital of England is London."],
            "capital of portugal": ["The capital of Portugal is Lisbon."],
            "capital of belgium": ["The capital of Belgium is Brussels."],
            "capital of mexico": ["The capital of Mexico is Mexico City."],
            "capital of canada": ["The capital of Canada is Ottawa."],
            "capital of australia": ["The capital of Australia is Canberra."],
            "capital of russia": ["The capital of Russia is Moscow."],
            "capital of china": ["The capital of China is Beijing."],
            "capital of japan": ["The capital of Japan is Tokyo."],
            "capital of india": ["The capital of India is New Delhi."],
            "capital of south africa": ["The capital of South Africa is Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial)."],
            "capital of nigeria": ["The capital of Nigeria is Abuja."],
            "capital of kenya": ["The capital of Kenya is Nairobi."],
            "capital of ethiopia": ["The capital of Ethiopia is Addis Ababa."],
            "capital of morocco": ["The capital of Morocco is Rabat."],
            "capital of tunisia": ["The capital of Tunisia is Tunis."],
            "capital of saudi arabia": ["The capital of Saudi Arabia is Riyadh."],
            "capital of united states": ["The capital of the United States is Washington, D.C."],
            "capital of turkey": ["The capital of Turkey is Ankara."],
            "capital of south Korea": ["The capital of South Korea is Seoul."],
            "capital of argentina": ["The capital of Argentina is Buenos Aires."],
            "capital of colombia": ["The capital of Colombia is Bogotá."],
            "capital of peru": ["The capital of Peru is Lima."],
            "capital of chile": ["The capital of Chile is Santiago."],
            "capital of venezuela": ["The capital of Venezuela is Caracas."],
            "capital of ecuador": ["The capital of Ecuador is Quito."],
            "capital of uruguay": ["The capital of Uruguay is Montevideo."],
            "capital of paraguay": ["The capital of Paraguay is Asunción."],
            "capital of bolivia": ["The capital of Bolivia is Sucre (constitutional) and La Paz (administrative)."],
            "capital of guyana": ["The capital of Guyana is Georgetown."],
            "capital of suriname": ["The capital of Suriname is Paramaribo."],
            "capital of australia": ["The capital of Australia is Canberra."],
            "capital of new Zealand": ["The capital of New Zealand is Wellington."],
            "capital of fiji": ["The capital of Fiji is Suva."],
            "capital of papua New Guinea": ["The capital of Papua New Guinea is Port Moresby."],
            "capital of solomon Islands": ["The capital of Solomon Islands is Honiara."],
            "capital of samoa": ["The capital of Samoa is Apia."],
            "capital of tonga": ["The capital of Tonga is Nuku'alofa."],
            "capital of vanuatu": ["The capital of Vanuatu is Port Vila."],
            "capital of nauru": ["The capital of Nauru is Yaren District."],
            "capital of tuvalu": ["The capital of Tuvalu is Funafuti."],
            "capital of kiribati": ["The capital of Kiribati is South Tarawa."],
            "capital of marshall islands": ["The capital of Marshall Islands is Majuro."],
            "capital of micronesia": ["The capital of Micronesia is Palikir."],
            "capital of palau": ["The capital of Palau is Ngerulmud."],
            "capital of belize": ["The capital of Belize is Belmopan."],
            "capital of costa rica": ["The capital of Costa Rica is San José."],
            "capital of el salvador": ["The capital of El Salvador is San Salvador."],
            "capital of guatemala": ["The capital of Guatemala is Guatemala City."],
            "capital of honduras": ["The capital of Honduras is Tegucigalpa."],
            "capital of nicaragua": ["The capital of Nicaragua is Managua."],
            "capital of panama": ["The capital of Panama is Panama City."],
            "capital of canada": ["The capital of Canada is Ottawa."],
            "capital of United States": ["The capital of the United States is Washington, D.C."],
            "capital of Mexico": ["The capital of Mexico is Mexico City."],
            "capital of Argentina": ["The capital of Argentina is Buenos Aires."],
            "capital of Brazil": ["The capital of Brazil is Brasília."],
            "capital of Colombia": ["The capital of Colombia is Bogotá."],
            "capital of Peru": ["The capital of Peru is Lima."],
            "capital of Venezuela": ["The capital of Venezuela is Caracas."],
            "capital of Chile": ["The capital of Chile is Santiago."],
            "capital of Ecuador": ["The capital of Ecuador is Quito."],
            "capital of Bolivia": ["The capital of Bolivia is Sucre (constitutional) and La Paz (administrative)."],
            "capital of Paraguay": ["The capital of Paraguay is Asunción."],
            "capital of Uruguay": ["The capital of Uruguay is Montevideo."],
            "capital of Belgium": ["The capital of Belgium is Brussels."],
            "capital of France": ["The capital of France is Paris."],
            "capital of Germany": ["The capital of Germany is Berlin."],
            "capital of Italy": ["The capital of Italy is Rome."],
            "capital of Spain": ["The capital of Spain is Madrid."],
            "capital of Portugal": ["The capital of Portugal is Lisbon."],
            "capital of United Kingdom": ["The capital of the United Kingdom is London."],
            "capital of Ireland": ["The capital of Ireland is Dublin."],
            "capital of Netherlands": ["The capital of the Netherlands is Amsterdam."],
            "capital of Switzerland": ["The capital of Switzerland is Bern."],
            "capital of Austria": ["The capital of Austria is Vienna."],
            "capital of Hungary": ["The capital of Hungary is Budapest."],
            "capital of Poland": ["The capital of Poland is Warsaw."],
            "capital of Sweden": ["The capital of Sweden is Stockholm."],
            "capital of Norway": ["The capital of Norway is Oslo."],
            "capital of Denmark": ["The capital of Denmark is Copenhagen."],
            "capital of Finland": ["The capital of Finland is Helsinki."],
            "capital of Greece": ["The capital of Greece is Athens."],
            "capital of Russia": ["The capital of Russia is Moscow."],
            "capital of China": ["The capital of China is Beijing."],
            "capital of Japan": ["The capital of Japan is Tokyo."],
            "capital of India": ["The capital of India is New Delhi."],
            "capital of South Korea": ["The capital of South Korea is Seoul."],
            "capital of Australia": ["The capital of Australia is Canberra."],
            "capital of New Zealand": ["The capital of New Zealand is Wellington."],
            "capital of South Africa": ["The capital of South Africa is Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial)."],
            "capital of Nigeria": ["The capital of Nigeria is Abuja."],
            "capital of Kenya": ["The capital of Kenya is Nairobi."],
            "capital of Ethiopia": ["The capital of Ethiopia is Addis Ababa."],
            "capital of Morocco": ["The capital of Morocco is Rabat."],
            "capital of Tunisia": ["The capital of Tunisia is Tunis."],
            "capital of Algeria": ["The capital of Algeria is Algiers."],
            "capital of Egypt": ["The capital of Egypt is Cairo."],
            "capital of Libya": ["The capital of Libya is Tripoli."],
            "capital of Sudan": ["The capital of Sudan is Khartoum."],
            "capital of Chad": ["The capital of Chad is N'Djamena."],
            "capital of Niger": ["The capital of Niger is Niamey."],
            "capital of Mali": ["The capital of Mali is Bamako."],
            "capital of Mauritania": ["The capital of Mauritania is Nouakchott."],
            "capital of Senegal": ["The capital of Senegal is Dakar."],
            "capital of Gambia": ["The capital of Gambia is Banjul."],
            "capital of Guinea-Bissau": ["The capital of Guinea-Bissau is Bissau."],
            "capital of Guinea": ["The capital of Guinea is Conakry."],
            "capital of Sierra Leone": ["The capital of Sierra Leone is Freetown."],
            "capital of Liberia": ["The capital of Liberia is Monrovia."],
            "capital of Ivory Coast": ["The capital of Ivory Coast is Yamoussoukro."],
            "capital of ghana": ["The capital of Ghana is Accra."],
            "capital of togo": ["The capital of Togo is Lomé."],
            "capital of Benin": ["The capital of Benin is Porto-Novo (official) and Cotonou (de facto)."],
            "capital of nigeria": ["The capital of Nigeria is Abuja."],
            "capital of cameroon": ["The capital of Cameroon is Yaoundé."],
            "capital of central african republic": ["The capital of Central African Republic is Bangui."],
            "capital of congo": ["The capital of Congo is Brazzaville."],
            "capital of gabon": ["The capital of Gabon is Libreville."],
            "capital of democratic republic of the congo": ["The capital of the Democratic Republic of the Congo is Kinshasa."],
            "capital of uganda": ["The capital of Uganda is Kampala."],
            "capital of kenya": ["The capital of Kenya is Nairobi."],
            "capital of rwanda": ["The capital of Rwanda is Kigali."],
            "capital of burundi": ["The capital of Burundi is Bujumbura."],
            "capital of tanzania": ["The capital of Tanzania is Dodoma (official) and Dar es Salaam (administrative)."],
            "capital of angola": ["The capital of Angola is Luanda."],
            "capital of zambia": ["The capital of Zambia is Lusaka."],
            "capital of malawi": ["The capital of Malawi is Lilongwe."],
            "capital of mozambique": ["The capital of Mozambique is Maputo."],
            "capital of namibia": ["The capital of Namibia is Windhoek."],
            "capital of zimbabwe": ["The capital of Zimbabwe is Harare."],
            "capital of botswana": ["The capital of Botswana is Gaborone."],
            "capital of lesotho": ["The capital of Lesotho is Maseru."],
            "capital of eswatini": ["The capital of Eswatini is Mbabane (administrative) and Lobamba (legislative)."],
            "capital of south africa": ["The capital of South Africa is Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial)."],
            "capital of argentina": ["The capital of Argentina is Buenos Aires."],
            "capital of bolivia": ["The capital of Bolivia is Sucre (constitutional) and La Paz (administrative)."],
            "capital of brazil": ["The capital of Brazil is Brasília."],
            "capital of Chile": ["The capital of Chile is Santiago."],
            "capital of Colombia": ["The capital of Colombia is Bogotá."],
            "capital of Ecuador": ["The capital of Ecuador is Quito."],
            "capital of Guyana": ["The capital of Guyana is Georgetown."],
            "capital of Paraguay": ["The capital of Paraguay is Asunción."],
            "capital of Peru": ["The capital of Peru is Lima."],
            "capital of Suriname": ["The capital of Suriname is Paramaribo."],
            "capital of Uruguay": ["The capital of Uruguay is Montevideo."],
            "capital of Venezuela": ["The capital of Venezuela is Caracas."],
            "capital of Afghanistan": ["The capital of Afghanistan is Kabul."],
            "capital of Armenia": ["The capital of Armenia is Yerevan."],
            "capital of Azerbaijan": ["The capital of Azerbaijan is Baku."],
            "capital of Bahrain": ["The capital of Bahrain is Manama."],
            "capital of Bangladesh": ["The capital of Bangladesh is Dhaka."],
            "capital of Bhutan": ["The capital of Bhutan is Thimphu."],
            "capital of Brunei": ["The capital of Brunei is Bandar Seri Begawan."],
            "capital of Cambodia": ["The capital of Cambodia is Phnom Penh."],
            "capital of Cyprus": ["The capital of Cyprus is Nicosia."],
            "capital of Georgia": ["The capital of Georgia is Tbilisi."],
            "capital of India": ["The capital of India is New Delhi."],
            "capital of Indonesia": ["The capital of Indonesia is Jakarta."],
            "capital of Iran": ["The capital of Iran is Tehran."],
            "capital of Iraq": ["The capital of Iraq is Baghdad."],
            "capital of Israel": ["Who the Hell is Israel"],
            "capital of Jordan": ["The capital of Jordan is Amman."],
            "capital of Kazakhstan": ["The capital of Kazakhstan is Nur-Sultan."],
            "capital of Kuwait": ["The capital of Kuwait is Kuwait City."],
            "capital of Kyrgyzstan": ["The capital of Kyrgyzstan is Bishkek."],
            "capital of Laos": ["The capital of Laos is Vientiane."],
            "capital of Lebanon": ["The capital of Lebanon is Beirut."],
            "capital of Malaysia": ["The capital of Malaysia is Kuala Lumpur."],
            "capital of Maldives": ["The capital of Maldives is Malé."],
            "capital of Mongolia": ["The capital of Mongolia is Ulaanbaatar."],
            "capital of Myanmar": ["The capital of Myanmar is Naypyidaw."],
            "capital of nepal": ["The capital of Nepal is Kathmandu."],
            "capital of north korea": ["The capital of North Korea is Pyongyang."],
            "capital of oman": ["The capital of Oman is Muscat."],
            "capital of pakistan": ["The capital of Pakistan is Islamabad."],
            "capital of palestine": ["The capital of Palestine is East Jerusalem."],
            "capital of philippines": ["The capital of Philippines is Manila."],
            "capital of qatar": ["The capital of Qatar is Doha."],
            "capital of saudi arabia": ["The capital of Saudi Arabia is Riyadh."],
            "capital of singapore": ["The capital of Singapore is Singapore."],
            "capital of south korea": ["The capital of South Korea is Seoul."],
            "capital of sri lanka": ["The capital of Sri Lanka is Colombo (executive and judicial) and Sri Jayawardenepura Kotte (legislative)."],
            "capital of syria": ["The capital of Syria is Damascus."],
            "capital of taiwan": ["The capital of Taiwan is Taipei."],
            "capital of tajikistan": ["The capital of Tajikistan is Dushanbe."],
            "capital of thailand": ["The capital of Thailand is Bangkok."],
            "capital of timor-leste": ["The capital of Timor-Leste is Dili."],
            "capital of turkey": ["The capital of Turkey is Ankara."],
            "capital of turkmenistan": ["The capital of Turkmenistan is Ashgabat."],
            "capital of united arab emirates": ["The capital of the United Arab Emirates is Abu Dhabi."],
            "capital of uzbekistan": ["The capital of Uzbekistan is Tashkent."],
            "capital of vietnam": ["The capital of Vietnam is Hanoi."],
            "capital of yemen": ["The capital of Yemen is Sana'a."],
            "capital of australia": ["The capital of Australia is Canberra."],
            "capital of fiji": ["The capital of Fiji is Suva."],
            "capital of kiribati": ["The capital of Kiribati is South Tarawa."],
            "capital of marshall Islands": ["The capital of Marshall Islands is Majuro."],
            "capital of micronesia": ["The capital of Micronesia is Palikir."],
            "capital of nauru": ["The capital of Nauru is Yaren District."],
            "capital of new zealand": ["The capital of New Zealand is Wellington."],
            "capital of palau": ["The capital of Palau is Ngerulmud."],
            "capital of papua new guinea": ["The capital of Papua New Guinea is Port Moresby."],
            "capital of samoa": ["The capital of Samoa is Apia."],
            "capital of solomon islands": ["The capital of Solomon Islands is Honiara."],
            "capital of tonga": ["The capital of Tonga is Nuku'alofa."],
            "capital of tuvalu": ["The capital of Tuvalu is Funafuti."],
            "capital of vanuatu": ["The capital of Vanuatu is Port Vila."],
            "capital of algeria": ["The capital of Algeria is Algiers."],
            "capital of angola": ["The capital of Angola is Luanda."],
            "capital of benin": ["The capital of Benin is Porto-Novo (official) and Cotonou (de facto)."],
            "capital of botswana": ["The capital of Botswana is Gaborone."],
            "capital of burkina Faso": ["The capital of Burkina Faso is Ouagadougou."],
            "capital of burundi": ["The capital of Burundi is Bujumbura."],
            "capital of cape Verde": ["The capital of Cape Verde is Praia."],
            "capital of cameroon": ["The capital of Cameroon is Yaoundé."],
            "capital of central african aepublic": ["The capital of Central African Republic is Bangui."],
            "capital of chad": ["The capital of Chad is N'Djamena."],
            "capital of comoros": ["The capital of Comoros is Moroni."],
            "capital of congo": ["The capital of Congo is Brazzaville."],
            "capital of democratic republic of the congo": ["The capital of the Democratic Republic of the Congo is Kinshasa."],
            "capital of Djibouti": ["The capital of Djibouti is Djibouti City."],
            "capital of egypt": ["The capital of Egypt is Cairo."],
            "capital of equatorial guinea": ["The capital of Equatorial Guinea is Malabo."],
            "capital of eritrea": ["The capital of Eritrea is Asmara."],
            "capital of eswatini": ["The capital of Eswatini is Mbabane (administrative) and Lobamba (legislative)."],
            "capital of ethiopia": ["The capital of Ethiopia is Addis Ababa."],
            "capital of gabon": ["The capital of Gabon is Libreville."],
            "capital of gambia": ["The capital of Gambia is Banjul."],
            "capital of ghana": ["The capital of Ghana is Accra."],
            "capital of guinea": ["The capital of Guinea is Conakry."],
            "capital of guinea-Bissau": ["The capital of Guinea-Bissau is Bissau."],
            "capital of ivory Coast": ["The capital of Ivory Coast is Yamoussoukro."],
            "capital of kenya": ["The capital of Kenya is Nairobi."],
            "capital of lesotho": ["The capital of Lesotho is Maseru."],
            "capital of liberia": ["The capital of Liberia is Monrovia."],
            "capital of libya": ["The capital of Libya is Tripoli."],
            "capital of madagascar": ["The capital of Madagascar is Antananarivo."],
            "capital of malawi": ["The capital of Malawi is Lilongwe."],
            "capital of mali": ["The capital of Mali is Bamako."],
            "capital of mauritania": ["The capital of Mauritania is Nouakchott."],
            "capital of mauritius": ["The capital of Mauritius is Port Louis."],
            "capital of morocco": ["The capital of Morocco is Rabat."],
            "capital of mozambique": ["The capital of Mozambique is Maputo."],
            "capital of namibia": ["The capital of Namibia is Windhoek."],
            "capital of niger": ["The capital of Niger is Niamey."],
            "capital of nigeria": ["The capital of Nigeria is Abuja."],
            "capital of rwanda": ["The capital of Rwanda is Kigali."],
            "capital of sao tome and pincipe": ["The capital of Sao Tome and Principe is Sao Tome."],
            "capital of senegal": ["The capital of Senegal is Dakar."],
            "capital of seychelles": ["The capital of Seychelles is Victoria."],
            "capital of sierra Leone": ["The capital of Sierra Leone is Freetown."],
            "capital of somalia": ["The capital of Somalia is Mogadishu."],
            "capital of south africa": ["The capital of South Africa is Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial)."],
            "capital of south sudan": ["The capital of South Sudan is Juba."],
            "capital of sudan": ["The capital of Sudan is Khartoum."],
            "capital of tanzania": ["The capital of Tanzania is Dodoma (official) and Dar es Salaam (administrative)."],
            "capital of togo": ["The capital of Togo is Lomé."],
            "capital of tunisia": ["The capital of Tunisia is Tunis."],
            "capital of uganda": ["The capital of Uganda is Kampala."],
            "capital of zambia": ["The capital of Zambia is Lusaka."],
            "capital of zimbabwe": ["The capital of Zimbabwe is Harare."],
            "capital of argentina": ["The capital of Argentina is Buenos Aires."],
            "capital of bolivia": ["The capital of Bolivia is Sucre (constitutional) and La Paz (administrative)."],
            "capital of brazil": ["The capital of Brazil is Brasília."],
            "capital of chile": ["The capital of Chile is Santiago."],
            "capital of colombia": ["The capital of Colombia is Bogotá."],
            "capital of ecuador": ["The capital of Ecuador is Quito."],
            "capital of guyana": ["The capital of Guyana is Georgetown."],
            "capital of paraguay": ["The capital of Paraguay is Asunción."],
            "capital of peru": ["The capital of Peru is Lima."],
            "capital of suriname": ["The capital of Suriname is Paramaribo."],
            "capital of uruguay": ["The capital of Uruguay is Montevideo."],
            "capital of venezuela": ["The capital of Venezuela is Caracas."],
            "capital of afghanistan": ["The capital of Afghanistan is Kabul."],
            "capital of armenia": ["The capital of Armenia is Yerevan."],
            "capital of azerbaijan": ["The capital of Azerbaijan is Baku."],
            "capital of bahrain": ["The capital of Bahrain is Manama."],
            "capital of bangladesh": ["The capital of Bangladesh is Dhaka."],
            "capital of bhutan": ["The capital of Bhutan is Thimphu."],
            "capital of brunei": ["The capital of Brunei is Bandar Seri Begawan."],
            "capital of cambodia": ["The capital of Cambodia is Phnom Penh."],
            "capital of cyprus": ["The capital of Cyprus is Nicosia."],
            "capital of georgia": ["The capital of Georgia is Tbilisi."],
            "capital of india": ["The capital of India is New Delhi."],
            "capital of indonesia": ["The capital of Indonesia is Jakarta."],
            "capital of iran": ["The capital of Iran is Tehran."],
            "capital of iraq": ["The capital of Iraq is Baghdad."],
            "who is messi": ["Lionel Messi is an Argentine professional footballer who plays as a forward."],
            "who is ronaldo": ["Cristiano Ronaldo is a Portuguese professional footballer who plays as a forward."],
            "neymar jr.": ["Neymar Jr. is a Brazilian professional footballer who plays as a forward."],
            "kylian mbappé": ["Kylian Mbappé is a French professional footballer who plays as a forward."],
            "virgil van dijk": ["Virgil van Dijk is a Dutch professional footballer who plays as a center-back."],
            "sergio ramos": ["Sergio Ramos is a Spanish professional footballer who plays as a center-back."],
            "robert lewandowski": ["Robert Lewandowski is a Polish professional footballer who plays as a forward."],
            "kevin de bruyne": ["Kevin De Bruyne is a Belgian professional footballer who plays as a midfielder."],
            "harry kane": ["Harry Kane is an English professional footballer who plays as a forward."],
            "mohamed salah": ["Mohamed Salah is an Egyptian professional footballer who plays as a forward."],
            "luka modric": ["Luka Modric is a Croatian professional footballer who plays as a midfielder."],
            "eden hazard": ["Eden Hazard is a Belgian professional footballer who plays as a forward."],
            "football clubs": ["Football clubs are organizations or teams that participate in professional football competitions. They are typically privately owned and consist of players, coaches, and support staff. Some of the most famous football clubs include Real Madrid, Barcelona, Manchester United, Bayern Munich, and Juventus."],
            "what is madrid": ["Real Madrid is a club from Spain.", "It is one of the most successful football clubs in the world."],
            "barcelona": ["Barcelona is a club from Spain.", "It is known for its tiki-taka style of play and has won numerous domestic and international titles."],
            "manchester united": ["Manchester United is a club from England.", "It has a rich history and has won numerous domestic and international titles, including the UEFA Champions League."],
            "bayern munich": ["Bayern Munich is a club from Germany.", "It is one of the most successful football clubs in Europe and has a strong domestic dominance in the Bundesliga."],
            "juventus": ["Juventus is a club from Italy.", "It is known for its strong defense and has won multiple Serie A titles."],
            "psg": ["Paris Saint-Germain (PSG) is a club from France.", "It is known for its wealthy ownership and has attracted top players from around the world."],
            "liverpool": ["Liverpool is a club from England.", "It has a passionate fanbase and has won numerous domestic and international titles, including the UEFA Champions League."],
            "manchester city": ["Manchester City is a club from England.", "It has experienced significant success in recent years, winning multiple Premier League titles."],
            "chelsea": ["Chelsea is a club from England.", "It has won multiple domestic and international titles, including the UEFA Champions League."],
            "ac milan": ["AC Milan is a club from Italy.", "It has a rich history and has won numerous domestic and international titles, including the UEFA Champions League."],
            "inter milan": ["Inter Milan is a club from Italy.", "It has a strong domestic presence and has won multiple Serie A titles."],
            "ajax": ["Ajax is a club from the Netherlands.", "It is known for its youth development and attractive style of play."],
            "boca juniors": ["Boca Juniors is a club from Argentina.", "It has a passionate fanbase and has won multiple domestic and international titles."],
            "river plate": ["River Plate is a club from Argentina.", "It has a strong rivalry with Boca Juniors and has won multiple domestic and international titles."],
            "flamengo": ["Flamengo is a club from Brazil.", "It has a large fanbase and has won numerous domestic and international titles."],
            "santos": ["Santos is a club from Brazil.", "It is known for producing talented players, including Pelé."],
            "galatasaray": ["Galatasaray is a club from Turkey.", "It has a passionate fanbase and has won multiple domestic and international titles."],
            "fenerbahçe": ["Fenerbahçe is a club from Turkey.", "It has a strong fanbase and has won multiple domestic titles."],
            "benfica": ["Benfica is a club from Portugal.", "It has a rich history and has won numerous domestic and international titles."],
            "porto": ["Porto is a club from Portugal.", "It has a strong domestic presence and has won multiple domestic and international titles."],
            "africa sports": ["Africa Sports is a club from Ivory Coast.", "It has a strong fanbase and has won multiple domestic titles."],
            "al ahly": ["Al Ahly is a club from Egypt.", "It is one of the most successful clubs in Africa and has won numerous domestic and continental titles."],
            "esperance": ["Espérance is a club from Tunisia.", "It has a strong presence in African football and has won multiple domestic and continental titles."],
            "sundowns": ["Mamelodi Sundowns is a club from South Africa.", "It is one of the most successful clubs in South Africa and has won numerous domestic and continental titles."],
            "al hilal": ["Al Hilal is a club from Saudi Arabia.", "It has a strong presence in Asian football and has won multiple domestic and continental titles."],
            "guangzhou evergrande": ["Guangzhou Evergrande is a club from China.", "It has been dominant in Chinese football and has won multiple domestic and continental titles."],
            "kashima antlers": ["Kashima Antlers is a club from Japan.", "It has been successful in Japanese football and has won multiple domestic and continental titles."],
            "auckland city": ["Auckland City is a club from New Zealand.", "It has been dominant in OFC Champions League and has represented OFC in FIFA Club World Cup."],
            "la galaxy": ["LA Galaxy is a club from the United States.", "It is one of the most successful clubs in Major League Soccer (MLS) and has attracted top players from around the world."],
            "orlando pirates": ["Orlando Pirates is a club from South Africa.", "It has a strong presence in South African football and has won multiple domestic and continental titles."],
            "rangers": ["Rangers is a club from Scotland.", "It has a strong rivalry with Celtic and has won numerous domestic titles."],
            "celtic": ["Celtic is a club from Scotland.", "It has a strong rivalry with Rangers and has won numerous domestic titles."],
            "bayer leverkusen": ["Bayer Leverkusen is a club from Germany.", "It has been successful in German football and has reached the UEFA Champions League final."],
            "as monaco": ["AS Monaco is a club from France.", "It has a strong presence in French football and has won multiple domestic titles."],
            "borussia dortmund": ["Borussia Dortmund is a club from Germany.", "It has a passionate fanbase and has won multiple domestic titles."],
            "rb leipzig": ["RB Leipzig is a club from Germany.", "It has rapidly risen through the ranks and has become a strong competitor in the Bundesliga."],
            "shanghai sipg": ["Shanghai SIPG is a club from China.", "It has been successful in Chinese football and has won multiple domestic titles."],
            "sevilla": ["Sevilla is a club from Spain.", "It has a strong presence in Spanish football and has won multiple domestic and international titles."],
            "valencia": ["Valencia is a club from Spain.", "It has a rich history and has won multiple domestic and international titles."],
            "athletic bilbao": ["Athletic Bilbao is a club from Spain.", "It is known for its policy of only fielding players of Basque origin and has won multiple domestic titles."],
            "ajax amsterdam": ["Ajax Amsterdam is a club from the Netherlands.", "It is known for its youth development and attractive style of play."],
            "fc porto": ["FC Porto is a club from Portugal.", "It has a strong domestic presence and has won multiple domestic and international titles."],
            "benfica lisbon": ["Benfica Lisbon is a club from Portugal.", "It has a rich history and has won numerous domestic and international titles."],
            "cruzeiro": ["Cruzeiro is a club from Brazil.", "It has a strong presence in Brazilian football and has won multiple domestic and continental titles."],
            "boca juniors": ["Boca Juniors is a club from Argentina.", "It has a passionate fanbase and has won multiple domestic and international titles."],
            "river plate": ["River Plate is a club from Argentina.", "It has a strong rivalry with Boca Juniors and has won multiple domestic and international titles."],
            "chivas guadalajara": ["Chivas Guadalajara is a club from Mexico.", "It is one of the most successful clubs in Mexican football and has won numerous domestic titles."],
            "club america": ["Club América is a club from Mexico.", "It has a strong fanbase and has won numerous domestic and international titles."],
            "olimpia": ["Club Olimpia is a club from Paraguay.", "It has a strong presence in Paraguayan football and has won multiple domestic and continental titles."],
            "peñarol": ["Peñarol is a club from Uruguay.", "It has a rich history and has won numerous domestic and international titles."],
            "nacional": ["Club Nacional is a club from Uruguay.", "It has a strong presence in Uruguayan football and has won multiple domestic and continental titles."],
            "tell me about ronaldinho": ["Ronaldinho is a professional footballer who plays as a LWF and CAM."],
            "who is the best football player": ["There are many great football players, and opinions may vary. Some notable players include Lionel Messi, Cristiano Ronaldo, and Neymar Jr."],
            "who won the last FIFA World Cup": ["France won the last FIFA World Cup in 2018."],
            "who is the current Ballon d'Or winner": ["The current Ballon d'Or winner is Karim Benzima."],
            "what is the highest transfer fee in football history": ["The highest transfer fee in football history is 220M, paid for the transfer of Neymar from Barrcelona to PSG."],
            "who is the most expensive player": ["The highest transfer fee in football history is 220M, paid for the transfer of Neymar from Barrcelona to PSG."],
            "who won the last champions league final": ["The next UEFA Champions League final is taken by Manchester City."],
            "what is the most successful football club": ["There are several successful football clubs, but some of the most successful ones include Barcelona, Real Madrid, and Manchester United."],
            "what is the oldest football club": ["The oldest football club is Cray Wanderers F.C., founded in 1860."],
            "tell me a football trivia": ["Sure, here's a football trivia: El Ifriki"],
            "what are the rules of football": ["Football is played between two teams, with each team aiming to score goals by kicking the ball into the opposing team's net. The team with the most goals at the end of the match wins."],
            "who is the all-time top scorer in the world": ["The all-time top scorer in the world is Cristiano Ronaldo, with 837 goals."],
            "what is the most-watched football match in history": ["The most-watched football match in history is 2010 FIFA WORLD CUP, with an estimated 715.1 viewers."],
            "what is the official FIFA World Cup anthem": ["The official FIFA World Cup anthem varies for each tournament. The most recent anthem was wavin flag for the 2010 World Cup."],
            "who is the highest-paid football player": ["The highest-paid football player is Cristiano Ronaldo, earning approximately 200M per year."],
            "what is the offside rule in football": ["The offside rule in football states that a player is in an offside position if they are nearer to the opposing team's goal line than both the ball and the second-to-last defender when the ball is played to them."],
            "who is the fastest football player": ["Some of the fastest football players include Kylian Mbappe, Haaland, and Kyle Walker."],
            "who is the best goalkeeper in the world": ["There are several talented goalkeepers in the world, including lev yashin, iker casillas, and buffon."],
            "who is the most successful football manager": ["Some of the most successful football managers include jose morino, pep goardiola, and nabil maaloul."],
            "president of united states": ["The President of the United States is Joe Biden."],
            "president of france": ["The President of France is Emmanuel Macron."],
            "president of germany": ["The President of Germany is Frank-Walter Steinmeier."],
            "president of brazil": ["The President of Brazil is Jair Bolsonaro."],
            "president of argentina": ["The President of Argentina is Alberto Fern?ndez."],
            "president of russia": ["The President of Russia is Vladimir Putin."],
            "president of china": ["The President of China is Xi Jinping."],
            "president of india": ["The President of India is Ram Nath Kovind."],
            "prime minister of japan": ["The Prime Minister of Japan is Yoshihide Suga."],
            "prime minister of canada": ["The Prime Minister of Canada is Justin Trudeau."],
            "prime minister of australia": ["The Prime Minister of Australia is Scott Morrison."],
            "president of south africa": ["The President of South Africa is Cyril Ramaphosa."],
            "earth": ["Earth is the third planet from the Sun and the only known astronomical object to support life.", "It has a diverse range of ecosystems and is home to millions of species."],
            "ocean": ["The ocean is a vast body of saltwater that covers approximately 71% of the Earth's surface.", "It plays a crucial role in regulating the planet's climate and is home to a rich variety of marine life."],
            "what is earth": ["Earth is the third planet from the Sun and the only known astronomical object to support life.", "It has a diverse range of ecosystems and is home to millions of species."],
            "what is ocean": ["The ocean is a vast body of saltwater that covers approximately 71% of the Earth's surface.", "It plays a crucial role in regulating the planet's climate and is home to a rich variety of marine life."],
            "tell me about earth": ["Earth is the third planet from the Sun and the only known astronomical object to support life.", "It has a diverse range of ecosystems and is home to millions of species."],
            "tell me about ocean": ["The ocean is a vast body of saltwater that covers approximately 71% of the Earth's surface.", "It plays a crucial role in regulating the planet's climate and is home to a rich variety of marine life."],
            "give me information about earth": ["Earth is the third planet from the Sun and the only known astronomical object to support life.", "It has a diverse range of ecosystems and is home to millions of species."],
            "give me information about ocean": ["The ocean is a vast body of saltwater that covers approximately 71% of the Earth's surface.", "It plays a crucial role in regulating the planet's climate and is home to a rich variety of marine life."],
            "can you work like calculateur":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "calculateur":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "you like calculateur":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "i like calculateur":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "i am falling in love with someone":["I hope that you will get well with him"],
            "can you do math":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "work like calculateur":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "calcule":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "math":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],    
            "add":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "+":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "can you help me in math":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "help me in math":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],    
            "in math":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "maths":["Yes i can do simple math operations like addition and andsubtraction and multiplication and division","Yes I can"],
            "greetings": ["Hello! How can I help you?", "Hi there! What can I do for you?"],
            "oceans general": ["Oceans cover about 71% of the Earth's surface."],
            "oceans importance": ["Oceans play a crucial role in regulating the Earth's climate and weather patterns."],
            "oceans biodiversity": ["Oceans are home to a diverse range of marine life, including fish, whales, dolphins, corals, and more."],
            "oceans resources": ["Oceans provide important resources such as food, energy, and minerals."],
            "oceans threats": ["Human activities, such as pollution, overfishing, and climate change, pose significant threats to the health of oceans."],
            "oceans exploration": ["Exploring and understanding the oceans is an ongoing scientific endeavor."],
            "oceans study": ["The study of oceans is known as oceanography."],
            "medina": ["The Medina of Tunis is a UNESCO World Heritage Site and a popular tourist attraction."],
            "bardo": ["The Bardo Museum is home to a vast collection of Roman mosaics and artifacts."],
            "what is sidi bou said": ["Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea."],
            "tunis mosque": ["The Great Mosque of Tunis is a significant religious site and an architectural masterpiece."],
            "cartage": ["Carthage, the ancient Roman city, is located near Tunis and is worth visiting for its historical ruins."],
            "the national museum of tunisia": ["The National Museum of Tunisia showcases the country's rich history and cultural heritage."],
            "dar ben abdellah": ["Dar Ben Abdallah is a traditional Tunisian house that provides insight into the local lifestyle and traditions."],
            "zitouna mosque": ["The Zitouna Mosque is the oldest mosque in Tunisia and an important religious landmark in Tunis."],
            "the national theatre of tunis":["The Tunisian National Theatre hosts various cultural events and performances throughout the year."],
            "the theatre of tunis": ["The Tunisian National Theatre hosts various cultural events and performances throughout the year."],
            "do you know the medina": ["The Medina of Tunis is a UNESCO World Heritage Site and a popular tourist attraction."],
            "do you know sidi bou said": ["Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea."],
            "where is sidi bou said": ["Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea."],
            "what you know about bardo": ["The Bardo Museum is home to a vast collection of Roman mosaics and artifacts."],
            "sidi bou said": ["Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea."],
            "mosque of tunis": ["The Great Mosque of Tunis is a significant religious site and an architectural masterpiece."],
            "what you know about cartage": ["Carthage, the ancient Roman city, is located near Tunis and is worth visiting for its historical ruins."],
            "the national museum of tunisia": ["The National Museum of Tunisia showcases the country's rich history and cultural heritage."],
            "do you know dar ben abdallah": ["Dar Ben Abdallah is a traditional Tunisian house that provides insight into the local lifestyle and traditions."],
            "zitouna": ["The Zitouna Mosque is the oldest mosque in Tunisia and an important religious landmark in Tunis."],
            "The Tunisian National Theatre": ["The Tunisian National Theatre hosts various cultural events and performances throughout the year."],
            "monster" : ["Monster Is Gharbi Oussama , He is the Owner of this Terminal , actually you dont Know anything about him"],
            "i am sad":["I am sorrey to hear that\n sometimes you pass a hard times makes you think that there is no meaning of your life \n but i think you will be fine Just try to skip that feeling by praying for god"],
            "sorry":["Don't be sorry anyone make mistakes","Don't apologize everyone can make wrong things"],
            "i am happy":["So happy to hear that"],
            "i am lonely":["The god always with you","You are wrong i am here with you"],
            "kshmir":["KSHMIR is a Free Fire Charecter and an artist he have many songs like : \n One More Round \n Close Your Eyes ..."],
            "alok":["Alok is a Free Fire Charecter and an artist he have many songs like : \n Vale Vale \n Headlights ..."],
            "sure":["i like when we agree"],
            "good":["yeah , i like when every thing is good","they say good things do still forever","great , anything else feel free to chat i am hear to keep you company"],
            "good job":["yeah , i like when every thing is good","they say good things do still forever","great , anything else feel free to chat i am hear to keep you company"],
            "about tunis": [
                "Tunis is the capital city of Tunisia, located in North Africa.",
                "It is known for its rich history, vibrant culture, and beautiful architecture.",
                "The city has many historical landmarks, such as the Medina of Tunis, a UNESCO World Heritage Site.",
                "Tunis is also a major economic and political center in the region.",
                "The city offers a variety of attractions, including museums, markets, and delicious local cuisine.",
                "If you're planning to visit Tunis, make sure to explore the famous Bardo Museum and the picturesque Sidi Bou Said village.",
                "Tunis experiences a Mediterranean climate with hot summers and mild winters.",
                "Arabic is the official language of Tunis, but French is widely spoken and understood.",
                "Tunis is a fascinating city that combines tradition and modernity, making it a great destination for travelers."
            ],
            
            "tunis info": [
                "The Medina of Tunis is a UNESCO World Heritage Site and a popular tourist attraction.",
                "The Bardo Museum is home to a vast collection of Roman mosaics and artifacts.",
                "Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea.",
                "The Great Mosque of Tunis is a significant religious site and an architectural masterpiece.",
                "Carthage, the ancient Roman city, is located near Tunis and is worth visiting for its historical ruins.",
                "The National Museum of Tunisia showcases the country's rich history and cultural heritage.",
                "Dar Ben Abdallah is a traditional Tunisian house that provides insight into the local lifestyle and traditions.",
                "The Zitouna Mosque is the oldest mosque in Tunisia and an important religious landmark in Tunis.",
                "The Tunisian National Theatre hosts various cultural events and performances throughout the year."
            ],    
            "tunis_general": [
                "Tunis is the capital city of Tunisia, located in North Africa.",
                "It is known for its rich history, vibrant culture, and beautiful architecture.",
                "The city has many historical landmarks, such as the Medina of Tunis, a UNESCO World Heritage Site.",
                "Tunis is also a major economic and political center in the region.",
                "The city offers a variety of attractions, including museums, markets, and delicious local cuisine.",
                "If you're planning to visit Tunis, make sure to explore the famous Bardo Museum and the picturesque Sidi Bou Said village.",
                "Tunis experiences a Mediterranean climate with hot summers and mild winters.",
                "Arabic is the official language of Tunis, but French is widely spoken and understood.",
                "Tunis is a fascinating city that combines tradition and modernity, making it a great destination for travelers."
            ],
            "tunisia places": [
                "The Medina of Tunis is a UNESCO World Heritage Site and a popular tourist attraction.",
                "The Bardo Museum is home to a vast collection of Roman mosaics and artifacts.",
                "Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea.",
                "The Great Mosque of Tunis is a significant religious site and an architectural masterpiece.",
                "Carthage, the ancient Roman city, is located near Tunis and is worth visiting for its historical ruins.",
                "The National Museum of Tunisia showcases the country's rich history and cultural heritage.",
                "Dar Ben Abdallah is a traditional Tunisian house that provides insight into the local lifestyle and traditions.",
                "The Zitouna Mosque is the oldest mosque in Tunisia and an important religious landmark in Tunis.",
                "The Tunisian National Theatre hosts various cultural events and performances throughout the year."
            ],  
            "tunisia": [
                "Tunis is the capital city of Tunisia, located in North Africa.",
                "It is known for its rich history, vibrant culture, and beautiful architecture.",
                "The city has many historical landmarks, such as the Medina of Tunis, a UNESCO World Heritage Site.",
                "Tunis is also a major economic and political center in the region.",
                "The city offers a variety of attractions, including museums, markets, and delicious local cuisine.",
                "If you're planning to visit Tunis, make sure to explore the famous Bardo Museum and the picturesque Sidi Bou Said village.",
                "Tunis experiences a Mediterranean climate with hot summers and mild winters.",
                "Arabic is the official language of Tunis, but French is widely spoken and understood.",
                "Tunis is a fascinating city that combines tradition and modernity, making it a great destination for travelers."
            ],
            "tunis landmarks": [
                "The Medina of Tunis is a UNESCO World Heritage Site and a popular tourist attraction.",
                "The Bardo Museum is home to a vast collection of Roman mosaics and artifacts.",
                "Sidi Bou Said is a charming blue and white village with beautiful architecture and stunning views of the Mediterranean Sea.",
                "The Great Mosque of Tunis is a significant religious site and an architectural masterpiece.",
                "Carthage, the ancient Roman city, is located near Tunis and is worth visiting for its historical ruins.",
                "The National Museum of Tunisia showcases the country's rich history and cultural heritage.",
                "Dar Ben Abdallah is a traditional Tunisian house that provides insight into the local lifestyle and traditions.",
                "The Zitouna Mosque is the oldest mosque in Tunisia and an important religious landmark in Tunis.",
                "The Tunisian National Theatre hosts various cultural events and performances throughout the year."
            ],
        }
        self.question_words = [
            "what",
            "the",
            "what is",
            "what's",
            "what is the",
            "what does it mean ",
            "what do you know about",
            "tell me about",
            "who",
            "who is",
            "chnie",
            "wchnie",
            "mean",
            "what it mean",
            "the mean of",
            "fsr",
            "tell me",
            "tell me about the",
            "what is",
            "fsr el",
        ]
    def respond(self,prompt):
        if any(prompt.lower().startswith(question_word) for question_word in self.question_words):
            for question_word in self.question_words:
                if prompt.lower().startswith(question_word):
                    question = prompt.split(question_word, 1)[1].strip()
                    if question or question.lower() in self.data:
                        try:
                            search_result = random.choice(self.data[question])
                        except:
                            search_result = random.choice(self.data[question.lower()])
                        return search_result
        elif prompt in self.data or prompt.lower() in self.data:
            try:
                search_result = random.choice(self.data[prompt])
            except:
                search_result = random.choice(self.data[prompt.lower()])
            return search_result
        else:
            try: 
                return eval(prompt)
            except:
                return None